### PR TITLE
use Github Actions

### PR DESCRIPTION
**Pull request by hamnis**
Builds on linux, macos and windows.

### CODE REVIEW

**Comment by hamnis** [comment]
We might need to patch the sbt plugin, but this might help.

https://github.com/oracle/graal/pull/2443

**Comment by hamnis** [comment]
https://github.com/scalameta/sbt-native-image/blob/main/.github/workflows/native.yml

**Comment by oyvindberg** [comment]
These links are for the failing windows build i disabled?

Feel free to continue working towards that, meanwhile i just wanted this in master right away

**Comment by hamnis** [comment]
@oyvindberg indeed they are.

**Pull request merged**
