### PR TITLE
Adds support for modulekindsplitstyle

### PR DESCRIPTION
**Pull request by KristianAN**
This is the same as:
https://github.com/oyvindberg/bleep/pull/391
Which I might or might not have pushed from my master, which I also might or might not have accidentaly overwritten.

I need some guidance with what is going on in the failing test here.

### CODE REVIEW

**Comment by oyvindberg** [comment]
this is the failing test. maybe there is an `@unchecked` somewhere which allows non-exhaustive pattern matches?

```
📗 BSP: - bleep.CreateNewSnapshotTests:
📗 BSP:   * create-new-build - scala.MatchError: Js (of class bleep.model.PlatformId$Js$)
```

**Comment by KristianAN** [comment]
That would live in bloop then? If so I will dig into it later tonight sometime

**Comment by oyvindberg** [comment]
no, in bleep. maybe in test code. you should be able to get a stack trace for that `MatchError` somehow

**Comment by KristianAN** [comment]
> no, in bleep. maybe in test code. you should be able to get a stack trace for that `MatchError` somehow

It was nothing but a simple bug in my code. Fixed now.

**Comment by oyvindberg** [comment]
I'll go ahead and merge this now. we'll fix in followups if anything is wrong

**Pull request merged**
