### PR TITLE
Update installing.mdx

### PR DESCRIPTION
**Pull request by KristianAN**
Updated information about installing for Nix.

### CODE REVIEW

**Comment by KristianAN** [comment]
GHA being deprecated, is there anything worse?

**Comment by nafg** [comment]
What do you mean

**Comment by KristianAN** [comment]
@nafg the build is failing because of this
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

**Comment by nafg** [comment]
So update it, or install Renovate or Dependabot and let them do it, why is that so bad?

**Comment by KristianAN** [comment]
Anything failing in GHA always feels bad :)

**Comment by oyvindberg** [comment]
I've tried to bump it in #420 . let's see if I can get it through. will merge this after 👍

**Pull request merged**
